version: '3.8'
services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://horus:horuspass@db:5432/horus_db
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
    depends_on:
      - db
      - rabbitmq

  notifier:
    build:
      context: ./workers/notifier
    restart: always
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
    depends_on:
      - rabbitmq

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=horus
      - POSTGRES_PASSWORD=horuspass
      - POSTGRES_DB=horus_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672" # Port for application communication
      - "15672:15672" # Port for the web management UI
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
volumes:
  postgres_data: