version: '3.8'
services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://horus:horuspass@db:5432/horus_db
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=horus
      - POSTGRES_PASSWORD=horuspass
      - POSTGRES_DB=horus_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: